#!/bin/bash
systemctl daemon-reload


START=0
BOUNCER_CONFIG_PATH="/etc/crowdsec/bouncers/crowdsec-openresty-bouncer.conf"
CERT_FILE=""
CERTS=(
    "/etc/pki/tls/certs/ca-bundle.crt"
    "/etc/pki/tls/cacert.pem"
    "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
    "/etc/ssl/certs/ca-bundle.crt"
    "/etc/ssl/certs/ca-certificates.crt"
)

check_lua_dependency() {
    DEPENDENCY=(
        "pintsized/lua-resty-http"
    )
    for dep in ${DEPENDENCY[@]};
    do
        opm list | grep ${dep} > /dev/null
        if [[ $? != 0 ]]; then
            opm get ${dep} > /dev/null && echo "${dep} successfully installed"     
        fi
    done
}



if [ "$1" = "configure" ]; then

    type cscli

    if [ "$?" -eq "0" ] ; then
        # Check if it's an upgrade
        if [ "$2" != "" ] ; then
            echo "Upgrading, check if there is bouncer configuration"
            if [ -f "${BOUNCER_CONFIG_PATH}" ] ; then
                START=2
            fi
        fi
        if [ ${START} -eq 0 ] ; then
            START=1
            echo "cscli/crowdsec is present, generating API key"
            unique=`date +%s`
            API_KEY=`cscli -oraw bouncers add crowdsec-openresty-bouncer-${unique}`
            CROWDSEC_LAPI_URL="http://127.0.0.1:8080"
            if [ $? -eq 1 ] ; then
                echo "failed to create API token, service won't be started."
                START=0
                API_KEY="<API_KEY>"
            else
                echo "API Key : ${API_KEY}"
            fi
        fi
    fi
    
    check_lua_dependency
    
    TMP=`mktemp -p /tmp/`
    cp ${BOUNCER_CONFIG_PATH} ${TMP}
    API_KEY=${API_KEY} CROWDSEC_LAPI_URL=${CROWDSEC_LAPI_URL} envsubst < ${TMP} > ${BOUNCER_CONFIG_PATH}
    rm ${TMP}
    TMP=`mktemp -p /tmp/`
    cp ${NGINX_CONFIG_PATH} ${TMP}
    for cert_path in ${CERTS[@]};
    do
        if [ -f $cert_path ]; then
            CERT_FILE=$cert_path
            break
        fi
    done
    SSL_CERTS_PATH=${CERT_FILE} envsubst < ${TMP} > ${NGINX_CONFIG_PATH}
    rm ${TMP}

    echo "Add 'include /usr/local/openresty/nginx/conf/conf.d/crowdsec_openresty.conf;' in your nginx configuration file to enable the bouncer."

else
    START=1
fi

if [ "$CERT_FILE" = "" ]; then
    START=0
    echo "Unable to find a valid certificate, please provide a valide certificate for the 'lua_ssl_trusted_certificate' directive in ${NGINX_CONFIG_PATH}."
fi

if [ ${START} -eq 0 ] ; then
    echo "Can't generate an API key for the bouncer. Please do it manually"
fi

echo "CrowdSec OpenResty Bouncer installed. Restart OpenResty service with 'sudo systemctl restart openresty'"
