name: release-package

on: 
  release:
    types:
      - prereleased

jobs:
  release-package:
    name: Upload release package
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: make the package
      run: make release

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        gh release upload "$tag_name" crowdsec-openresty-bouncer.tgz
